# -*- coding: utf-8 -*-
"""Modelo_Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pQaKcApDXJRyZBsdppqbRd_7Ml4kcH73

#Dados do Titanic

[Link dos Dados](https://www.kaggle.com/heptapod/titanic)

# Pacotes Necessários
"""

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

"""#Lendo o Banco de Dados"""

dados = pd.read_csv('/content/train.csv')

dados.head()

dados = dados.drop(['Name','Ticket','Cabin','Embarked'], axis = 1)

dados.head()

"""#Editando Chave e Variável de Resposta"""

dados = dados.set_index(['PassengerId'])
dados = dados.rename(columns = {'Survived':'target'},inplace = False)

dados.head()

"""#Descritiva"""

dados.describe()

dados.describe(include = ['O'])

"""#Transformação de Dados"""

dados['Sex_F'] = np.where(dados['Sex'] == 'female', 1, 0)

dados['Pclass_1'] = np.where(dados['Pclass'] == 1, 1, 0)
dados['Pclass_2'] = np.where(dados['Pclass'] == 2, 1, 0)
dados['Pclass_3'] = np.where(dados['Pclass'] == 3, 1, 0)

dados = dados.drop(['Pclass','Sex'], axis = 1)

dados.head()

dados.isnull().sum()

dados.fillna(0, inplace = True)

dados.isnull().sum()

"""#Amostragem"""

x_train, x_test, y_train, y_test = train_test_split(dados.drop(['target'], axis = 1),
                                                    dados["target"],
                                                    test_size = 0.3,
                                                    random_state = 1234)

[{'treino': x_train.shape},
 {'teste': x_test.shape}]

"""#Modelo"""

rndforest = RandomForestClassifier(n_estimators = 1000,
                                   criterion = 'gini',
                                   max_depth = 5)

rndforest.fit(x_train, y_train)

probabilidade = rndforest.predict_proba(dados.drop('target',axis = 1))[:,1]
classificacao = rndforest.predict(dados.drop('target',axis = 1))

"""####Probabilidade de Sobrevivência (Classificado em > 0,5)"""

dados['probabilidade'] = probabilidade
dados['classificacao'] = classificacao

dados